### ISSUE TITLE
Samba Dancing model does not display correctly

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#6]
I tried to display the Samba Dancing model below in CZPG.js.

http://examples.claygl.xyz/examples/basicModelAnimation.html

However, it was not displayed properly.

http://jsdo.it/cx20/wrxG
![image](https://user-images.githubusercontent.com/1833979/39614006-3a9fe00a-4fa7-11e8-9da7-cfbc593b037b.png)

**Comment by PrincessGod** [comment]
@cx20  are you sure this model show properly on other engines?

Cause I am not found bug in my loader...

**Comment by cx20** [comment]
> are you sure this model show properly on other engines?

I am confirming that this model is displayed in the following libraries. 

Three.js : http://jsdo.it/cx20/UqP9
Babylon.js : http://jsdo.it/cx20/Kxcp
PlayCanvas : http://jsdo.it/cx20/gHSE
ClayGL : http://jsdo.it/cx20/6KEi
Hilo3d : http://jsdo.it/cx20/8xUn

**Comment by PrincessGod** [comment]
I found this model's node use `matrix`, and maybe the reason is I get the wrong `jointMatrices`.

I will [decompose](https://github.com/PrincessGod/CraZyPG/blob/master/src/loaders/GLTFLoader.js#L229-L236) matrix into `TRS`, and there is [compute jointMatrices](https://github.com/PrincessGod/CraZyPG/blob/master/src/loaders/GLTFLoader.js#L441-L448).

Other skin works fine, so I guess matrix decompose makes wrong? but the VC.gltf model works fine with matrix node.

**Comment by PrincessGod** [comment]
@cx20  Fixed, thanks!

**Comment by cx20** [comment]
I confirmed that it works properly.
http://jsdo.it/cx20/wrxG
![image](https://user-images.githubusercontent.com/1833979/39661361-4c453d34-508b-11e8-854e-ad5e295c215a.png)
